### PR TITLE
fortls 2.13.0 (new formula)

### PR DESCRIPTION
**Pull request by awvwgk**
cc @gnikit

### CODE REVIEW

**Comment by gnikit** [comment]
we need these deps

```setup.cfg
    json5
    packaging
    importlib-metadata; python_version < "3.8"
    typing-extensions; python_version < "3.8"
```

**Comment by awvwgk** [comment]
There are no real dependencies in brew, rather you install all required packages in a venv, manually, and than use this to run the executable.

**Comment by gnikit** [comment]
> There are no real Python dependencies in brew, rather you install all required packages in a venv, manually, and than use this to run the executable.

Cool, does that mean we should also list as a "resource" the `[build-system] requires=[]` found in `pyproject.toml`?

**Comment by awvwgk** [comment]
I think, you basically get `pip install *.tar.gz --no-deps` for all resources in the venv, build dependencies are pulled in but not part of the final venv due to build isolation.

**Comment by gnikit** [comment]
I think `setuptools_scm` is a runtime dependency

**Pull request closed without merging**
