### PR TITLE
fpm 0.8.1

### PR DESCRIPTION
**Pull request by perazz**
Update formula to fpm release v0.8.1

### CODE REVIEW

**Comment by rouson** [comment]
@awvwgk any idea why the CI tests fail on this PR?

**Comment by awvwgk** [comment]
There is a clear text error message pointing to the problem:

```
==> FAILED
Full style fortran-lang/fortran output
  /usr/local/Homebrew/Library/Taps/fortran-lang/homebrew-fortran/Formula/fpm.rb:20:12: C: FormulaAudit/Miscellaneous: Use the pwd Ruby method instead of system "pwd"
      system "pwd"
             ^^^^^
  
  3 files inspected, 1 offense detected
  Error: FormulaAudit/Miscellaneous: Use the `pwd` Ruby method instead of `system "pwd"`
```

**Comment by perazz** [comment]
I'm sorry I'm still learning how to test formulas locally. 

I've found a first issue, probably due to the website certificate being expired
```
==> FAILED
Error: 1 problem in 1 formula detected
perazz/fortran/fpm:
  * The homepage URL https://fpm.fortran-lang.org is not reachable
```

**Comment by perazz** [comment]
Now all checks are passed, but in the logfile, I see: 
```
==> ./install.sh --prefix=/usr/local/Cellar/fpm/0.8.1 
Failed to execute: ./install.sh
```

**Comment by awvwgk** [comment]
Milan @milancurcic, could you have a look at the certificate for fpm.fortran-lang.org?

**Comment by milancurcic** [comment]
Certificates are provided by Let's Encrypt and automatically renewed by GitHub. I don't know why this one didn't get renewed, and it expired on April 25. I only navigated to https://github.com/fortran-lang/fpm-docs/settings/pages and saw the spinners that the certificate is being provisioned. The certificate now appears to be renewed and the page loads under HTTPS.🤷

**Comment by perazz** [comment]
It seems to be working now, appreciated your help @awvwgk @milancurcic

**Comment by awvwgk** [comment]
Can you squash this branch down to one commit before adding the pr-pull label?

**Comment by perazz** [comment]
pr-pull is failing due to a `git cherry-pick` issue. I will delete this branch and open a new PR with a single commit, let's see if that works.

**Pull request closed without merging**
